In [1]:
import pandas as pd
import numpy as np

In [2]:
pedalboards = pd.read_csv('data/pedalboard-plugin.csv')
pedalboards.columns = ['id', 'name', 0, 1, 2, 3, 4, 5]

pedalboards.head()

     id        name   0   1    2    3    4    5
0  9467    !!*Cuda'  23  27   73  109  106   61
1  8913  '70s*V.H**  39  30  100   60  107  107
2  7313  '70s*V.H**  39  30  100   60  107  107
3  9471  '70s*V.H**  39  30  100   60  107  107
4  7313  '90s*V.H**  23  99   31   42   53   60

In [3]:
plugins = pd.read_csv('data/plugin-category.csv', index_col='id')
plugins = plugins.sort_index()

plugins.head()

        name    category
id
0   M-Filter   Filter_EQ
1    TheVibe  Modulation
2    Z-Organ         SFX
3     Slicer  Modulation
4   PhaseDly       Delay

In [4]:
data = pd.DataFrame([], index=pedalboards.index, columns=plugins.index)
data = data.fillna(0)

data.head()

id,0,1,2,3,4,5,6,7,8,9,...,107,108,109,110,111,112,113,114,115,116
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
for index, pedalboard in pedalboards[[0, 1, 2, 3, 4, 5]].iterrows():
    for effect in pedalboard:
        if np.isnan(effect):
            continue
        data[effect][index] += 1

data.head()

id,0,1,2,3,4,5,6,7,8,9,...,107,108,109,110,111,112,113,114,115,116
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
new_index = pd.MultiIndex.from_tuples(list(zip(pedalboards.index.tolist(), pedalboards['id'].tolist())), names=['index', 'id'])
data.index = new_index

data.head()

,id,0,1,2,3,4,5,6,7,8,9,...,107,108,109,110,111,112,113,114,115,116
index,id,,,,,,,,,,,,,,,,,,,,,
0,9467,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,8913,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
2,7313,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
3,9471,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
4,7313,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
data.to_csv('data/pedalboard-plugin-bag-of-words.csv')

## Visualizar plugins de Ã¡udio

For data show, replace index for pedalboard name

In [8]:
plugins['Plugin'] = plugins.name
plugins['Category'] = plugins.category

data.columns = [plugins.Category, plugins.Plugin]

data.head()

Category   Filter_EQ Modulation     SFX Modulation    Delay            \
Plugin      M-Filter    TheVibe Z-Organ     Slicer PhaseDly FilterDly
index id
0     9467         0          0       0          0        0         0
1     8913         0          0       0          0        0         0
2     7313         0          0       0          0        0         0
3     9471         0          0       0          0        0         0
4     7313         0          0       0          0        0         0

Category                      Modulation    SFX  ...   None Amp Modeling  \
Plugin     PitchDly StereoDly   BitCrush Bomber  ...   None    TONE CITY
index id                                         ...
0     9467        0         0          0      0  ...      0            0
1     8913        0         0          0      0  ...      2            0
2     7313        0         0          0      0  ...      2            0
3     9471        0         0          0      0  ...      2            0
4     7313        0         0          0      0  ...      0            0

Category
Plugin     B-BREAKER BGN DRIVE DELUXE-R ALIEN REVO-1 CAR DRIVE MS 1959 VX JMI
index id
0     9467         1         0        0     0      0         0       0      0
1     8913         0         0        0     0      0         0       0      0
2     7313         0         0        0     0      0         0       0      0
3     9471         0         0        0     0      0         0       0      0
4     7313         0         0        0     0      0         0       0      0

[5 rows x 117 columns]